version: '3'

services:
  minecraft:
    image: openjdk:17-ea-slim
    working_dir: /app

    ports:
      - "25565:25565"
    volumes:
      - ./:/app
    environment:
      - MEMORY=3072
    command: [ "bash", "start.sh" ]

